#!/usr/bin/env python

"""
Tool file: bench_batch
"""

import sys
if sys.version_info.minor != 10:
    print("WARNING! Some functionality may not work with python3 version minor other than 10.")
import warnings
warnings.simplefilter("ignore", DeprecationWarning)
try:
    import pandas
except ModuleNotFoundError:
    msg = """Missing Pandas package, two possible causes:
    - The package is missing in the server installation.
    - You need to activate an enviroment to run MCCE4 locally.
    """
    sys.exit(msg)

from mcce4.mcce_benchmark.batch_submit import launch_cli


if __name__ == "__main__":
    sys.exit(launch_cli())
