#!/usr/bin/env python

"""
Tool file: getpdb (uses mcce4.protinfo)
Possibly download the bioassembly of one or more proteins, else download the standard pdb file.
"""

import logging
from mcce4 import argparse
from mcce4.protinfo.io_utils import get_rcsb_pdb

logging.getLogger("mcce4.protinfo.io_utils").setLevel(logging.WARNING)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="getpdb",
                                     description=("Download one or more (bioassembly) pdb files "
                                                  "from the RSCB download service."))
    parser.add_argument("pdbid", metavar="pdbid",
                        help="Specify the pdb ID(s), e.g.: 1ots 4lzt 1FAT",
                        nargs="+", default=[])
    args = parser.parse_args()
    pdbids = [id.lower() for id in args.pdbid]

    for pdbid in pdbids:
        out = get_rcsb_pdb(pdbid)
        if isinstance(out, tuple):
            msg = out[1] + "PDB id: " + pdbid
            print(msg)
        print("Downloaded:", pdbid)
