#!/usr/bin/env python

"""
Tools file: md_clustering
"""

import sys
try:
    import MDAnalysis as mda
except ModuleNotFoundError:
    msg = """
    Package `MDAnalysis` is required in this module. Activate an environment that includes it & try again."
    To install, activate a conda environment & run: `conda install -c conda-forge msdanalysis`
    """
    sys.exit(msg)

import argparse
from pathlib import Path
from typing import Union
import warnings
warnings.filterwarnings("ignore")
import MDAnalysis.analysis.encore as mda_encore


def example():
    text = """
    Given:
    ```
    > select_res="(backbone and (resid 22 173 194 226) and segid NDHA) or (backbone and (resid 87) and segid NDHC)"
    ```
    Commands:
    ```
    > cd my_md_files_dir  # optional
    > md_clustering some.psf traj1.dcd traj2.dcd -labels DCD1 DCD2 -selection $select_res
    ```
    Outcome:
    The pdbs of the cluster elements will be saved in the topology file's parent directory.
    """
    print(text)


def output_cluster_elements(args: Union[dict, argparse.Namespace]):
    """Main function.
    """
    if isinstance(args, dict):
        args = argparse.Namespace(**args)
    
    top_fp = Path(args.topology_file)
    if not top_fp.exists():
        sys.exit(f"\nTopology file not found: {str(top_fp)}")

    n_trajs = len(args.trajectory_files)
    n_labels = len(args.labels)

    if len(args.trajectory_files) > 1:
        # validate labels if any:
        if n_labels and n_labels != n_trajs:
            sys.exit("\nThe number of labels must match the number of trajectories.")
    # check traj files found:
    for traj in args.trajectory_files:
        if not Path(traj).exists():
            sys.exit(f"\nTrajectory file not found: {traj}")

    out_dir = top_fp.parent
    topo = str(top_fp)
    universes = []
    cluster_collections = []

    for i, traj in enumerate(args.trajectory_files):
        traj_lbl = args.labels[i]
        ui = mda.Universe(topo, traj)
        print(f"{traj_lbl} universe: ", ui, len(ui.trajectory))
        universes.append(ui)

        if args.selection:
            clui = mda_encore.cluster(ui, selection=args.selection)
        else:
            clui = mda_encore.cluster(ui)
        print(f"{traj_lbl} clusters: ", clui)
        cluster_collections.append(clui)

    for i, cluster_sets in enumerate(cluster_collections):
        traj_lbl = args.labels[i]

        clust_name = out_dir.joinpath(f"cluster_info_{traj_lbl}.txt")
        with open(clust_name, "w") as fo:
            fo.write(f"\n{traj_lbl}:\n")
            for cluster in cluster_sets:
                line = (f"{cluster.id}:: centroid: {cluster.centroid}, "
                        f"size: {cluster.size:,}, elements: {cluster.elements}\n")
                print(line)
                fo.write(line)
                for elem in cluster.elements:
                    universes[i].trajectory[elem]
                    pdb_fp = out_dir.joinpath(f"{traj_lbl}_clus_{cluster.id}_{elem}_frame.pdb")
                    with mda.Writer(pdb_fp) as pdb:
                        pdb.write(universes[i])

    print("Cluster analysis over.")


def cli_parser():
    p = argparse.ArgumentParser(
        description=("Cluster one or more MD trajectories and "
                     "return the elements in each cluster as pdb files."),
        usage=("\n> md_clustering some.psf traj1.dcd traj2.dcd -labels "
               "DCD1 DCD2 -selection my_selection"),
    )
    p.add_argument(
        "topology_file",
        help="Topology filename/path."
        )
    p.add_argument(
        "trajectory_files",
        nargs="+",
        help="Trajectory filepath or list thereof."
        )
    p.add_argument(
        "-labels",
        nargs="+",
        help="Labels for the cluster info to return."
        )
    p.add_argument(
        "-selection",
        required=False,
        default="",
        help="Atom selection over all the trajectories."
        )
    p.add_argument(
        "--show_example",
        default=False,
        action="store_true",
        help="Just show a call example.")
    return p


def cluster_cli(argv=None):
    p = cli_parser()
    args = p.parse_args(argv)
    if args.show_example:
        example()
    else:
        output_cluster_elements(args)


if __name__ == "__main__":
    sys.exit(cluster_cli())
