#!/usr/bin/env python3

"""
Tool file: pro_batch

NOTES:
1. The current implementation creates a submit script in the current working
   directory (cwd), and considers it as the master: this is where the users 
   would enter their modifications.
   The user's modifications will be used for each protein simulation as this
   master script file is soft-linked into each protein folder.
"""
import sys

from mcce4.probatch import cli


if __name__ == "__main__":
    sys.exit(cli())
