#!/usr/bin/env python
import os
import sys
import subprocess

# FUTRUE:
#from mcce4.p_info import p_info_solo, ...


def main():
    if len(sys.argv) != 2:
        print("Usage: python p_info_wrapper.py <input_file_or_directory>")
        sys.exit(1)

    input_path = sys.argv[1]

    # Get the path to the directory containing this script
    wrapper_dir = os.path.dirname(os.path.abspath(__file__))
    # Construct full paths to the executables
    p_info_path = os.path.join(wrapper_dir, 'mcce4', 'protinfo', 'p_info')
    p_info_batch_path = os.path.join(wrapper_dir, 'mcce4', 'protinfo', 'p_info_batch')

    if os.path.isdir(input_path):
        subprocess.run([p_info_batch_path, input_path])
        return

    if os.path.isfile(input_path):
        if not input_path.lower().endswith('.pdb'):
            subprocess.run([p_info_batch_path, input_path])
            return
        else:
            subprocess.run([p_info_path, input_path])
            return

    print(f"Error: '{input_path}' is not a valid file or directory.")

if __name__ == "__main__":
    main()

